name: Deploy
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Prepare publish
              run: |
                  mkdir -p publish
                  find . -name "*.md" -not -path "./.git/*" -not -name "README.md" | sed 's|^\./||' > md_files.txt
                  jq -R -s -c 'split("\n") | map(select(. != ""))' md_files.txt > publish/files.json
                  rm md_files.txt
                  mv public/* publish/

            # Publish
            - name: Publish Website
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./publish
                  keep_files: false
